### ISSUE TITLE
app exits after exception

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#1008]
**Describe the bug**

been getting a couple of these intermittenly tonight, going to open an issue to track information on this. Thinking some emit/handler parameter count mismatches.

Maybe related to a bunch of nodeFetch being issued at once.

**To Reproduce**
yarn start-prod

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

```
{"name":"log","hostname":"Admins-MacBook-Pro.local","pid":37600,"level":30,"msg":"draw attention","time":"2020-03-25T07:20:54.609Z","v":0}
Unhandled Error: TypeError: Insufficient number of arguments.
    at EventEmitter.<anonymous> (/Users/admin/Sites/loki-messenger/main.js:955:14)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/admin/Sites/loki-messenger/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
{"name":"log","hostname":"Admins-MacBook-Pro.local","pid":37600,"level":50,"msg":"Unhandled Error: TypeError: Insufficient number of arguments.\n    at EventEmitter.<anonymous> ([REDACTED]/loki-messenger/main.js:955:14)\n    at EventEmitter.emit (events.js:200:13)\n    at WebContents.<anonymous> ([REDACTED]/loki-messenger/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)\n    at WebContents.emit (events.js:200:13)","time":"2020-03-25T07:20:54.611Z","v":0}
error Command failed with exit code 1.
```

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by neuroscr** [comment]
I've tracked this down to `app.dock.bounce();` in main.js
