### ISSUE TITLE
GLIBC_2.25 not found error when trying to run session on Ubuntu 16.04

### ISSUE THREAD

**Issue by oren** [loki-project/session-desktop#1082]
**Describe the bug**
Error when running Session for ubuntu desktop: 
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.org.chromium.Chromium.40qkbz)
```

**To Reproduce**
Download session-messenger-desktop-linux-x86_64-1.0.6.AppImage

```
chmod 755 session-messenger-desktop-linux-x86_64-1.0.6.AppImage
./session-messenger-desktop-linux-x86_64-1.0.6.AppImage
```

**Screenshots or Logs**

```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /tmp/.mount_sessioxbUvao/resources/app.asar/config
NODE_CONFIG {}
userData: /home/oren/.config/Session
config/get: Did not find user config file, cache is now empty object
config/get: Did not find ephemeral config file, cache is now empty object
Unhandled Error: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.org.chromium.Chromium.40qkbz)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
Unhandled Error: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.org.chromium.Chromium.40qkbz)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
Unhandled Error
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.org.chromium.Chromium.40qkbz)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Other information (please complete the following information):**

* Device: PC
* OS: Ubuntu 16.04
* Session Version or Git commit hash: session-messenger-desktop-linux-x86_64-1.0.6.AppImage

**Comment by hueq** [comment]
I had the same issue of missing glibc 2.25 in Debian.

- OS: Debian 9 (stretch) with libc6 2.24-11+deb9u4
- Session: 1.0.6 amd64 (`session-messenger-desktop-linux-amd64-1.0.6.deb`)

I believe glibc is provided by package libc6 in Debian/Ubuntu.
Under Debian stretch it should be 2.24, and under Ubuntu xenial 2.23.
https://packages.debian.org/stretch/libc6
https://packages.ubuntu.com/xenial-updates/libc6

Assuming this is true, I guess upgrading to buster/bionic or installing a later libc6 might make Session work. But is there a fix that can make Session work in Debian stretch or Ubuntu xenial?

**Comment by Bilb** [comment]
As you can see [here](https://pkgs.org/download/libc6), the most recent libc6 version installed on xenial is 2.23 which is not enough for electron to run.
As said on the linked issue, the easiest way to fix this issue is to upgrade the system OS. Debian 10 Buster or Ubuntu Bionic 18.04 have both a recent enough libc6 version to run Electron and Electron apps in general. Maybe you can find a way to install libc6 v2.25 on your system while keeping the one currently installed.
