### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by KeeJef** [loki-project/session-desktop#870]
getting this error on windows desktop when launching from the installer after updating from a previous version. 

```Unhandled Promise Rejection

Error: Object has been destroyed
    at WebContents.send ([REDACTED]\electron.asar\browser\api\web-contents.js:112:15)
    at EventEmitter.ipcMain.on ([REDACTED]\app.asar\app\attachment_channel.js:45:20)
```

**Comment by neuroscr** [comment]
duplication of #893
